apiVersion: apps/v1
kind: Deployment
metadata:
  name: inc-appr-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inc-appr-ui
  template:
    metadata:
      labels:
        app: inc-appr-ui
    spec:
      containers:
        - name: inc-appr-ui
          image: internalappsdev1.azurecr.io/inc-appr-ui:__TAG__
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: inc-appr-ui
spec:
  type: LoadBalancer
  ports:
    - port: 3000
  selector:
    app: inc-appr-ui
