apiVersion : apps/v1
kind: Deployment
metadata:
  name: itm-ui-azuredemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itm-ui-azuredemo
  template:
    metadata:
      labels:
        app: itm-ui-azuredemo 
    spec:
      containers:
        - name: itm-ui-azuredemo 
          image: azuredemoincproducts.azurecr.io/itm-ui-azuredemo:__TAG__
          ports:
          - containerPort: 3000
     
--- 

  
apiVersion: v1
kind: Service
metadata:
    name: itm-ui-azuredemo
spec:
    type: ClusterIP
    ports:
    - port: 3000
    selector:
        app: itm-ui-azuredemo