apiVersion : apps/v1
kind: Deployment
metadata:
  name: inc-appre-portalui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inc-appre-portalui
  template:
    metadata:
      labels:
        app: inc-appre-portalui 
    spec:
      containers:
        - name: inc-appre-portalui 
          image: azuredemoincproducts.azurecr.io/inc-appre-portalui:"__tag__"
          ports:
          - containerPort: 3000
     
--- 

  
apiVersion: v1
kind: Service
metadata:
    name: inc-appre-portalui
spec:
    type: ClusterIP
    ports:
    - port: 3000
    selector:
        app: inc-appre-portalui